export declare class CloudRoutersPanel extends HTMLElement {
    private router;
    private states;
    private combosByRouter;
    private offProgress;
    private visibilityObserver;
    private refreshTimer;
    private root;
    private unsubUpdate?;
    constructor();
    private stateOf;
    private get status();
    private get combos();
    private setStatus;
    private setCombos;
    connectedCallback(): void;
    disconnectedCallback(): void;
    private observeVisibility;
    private refresh;
    private onProgress;
    private setBtnBusy;
    private notifyCombosChanged;
    private onInstall;
    private onOpen;
    private onStart;
    private onStop;
    private onShowCombos;
    private onSetDir;
    private onCheckUpdate;
    private onInstallUpdate;
    private switchRouter;
    private render;
    private renderUpdateState;
}
